# Generated by Django 5.0.3 on 2024-04-22 03:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='dob',
            field=models.DateField(default=datetime.date(2024, 4, 22)),
            preserve_default=False,
        ),
    ]
