# Generated by Django 5.0.3 on 2024-04-23 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0004_alter_customuser_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_forwarded_to_specialist',
            field=models.BooleanField(default=False),
        ),
    ]
