# Generated by Django 5.0.3 on 2024-04-23 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0005_appointment_is_forwarded_to_specialist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='status',
            new_name='patient_status',
        ),
    ]
