# Generated by Django 5.0.3 on 2024-04-23 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0007_alter_appointment_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_cared_for',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='is_prescribed',
            field=models.BooleanField(default=False),
        ),
    ]
