# Generated by Django 5.0.3 on 2024-04-23 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0008_appointment_is_cared_for_appointment_is_prescribed'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_fee',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointment_rate',
            field=models.DecimalField(decimal_places=2, default=8.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='appointment',
            name='consultation_fee',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='consultation_rate',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=10),
        ),
    ]
