# Generated by Django 5.0.3 on 2024-04-23 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0009_appointment_appointment_fee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='price',
        ),
    ]
