# Generated by Django 5.0.3 on 2024-04-24 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('newapp', '0011_remove_appointment_consultation_fee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
